version: '3.6'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default
  qiskit-service:
    image: planqk/qiskit-service:latest
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis
    networks:
      - default
networks:
  default:
    driver: bridge